#[derive(Debug, PartialEq)]
pub enum ReturnCode {
    OK,
    KeyNotFound,
    BLANK,
    ShiftFailure,
    ContainerInvalidSize,
    ExpandingContainerFailed,
    ExpandingCallocFailed,
    ExpandingNecessary,
    ChildContainerMissing,
    PointerOutOfContainerBound,

    PointerNull,
    PointerInvalid,
    AddValueFailure,
    PutFailureExpandFailed,
    PutFailureValueaddNeedsShift,
    PutFailureKeyaddNeedsShift,
    GetFailureTraverse,
    GetFailureNoNode,
    GetFailureNoLeaf,
    UnknownOperation,
    INITIAL,
}
